FROM golang:alpine as builder
RUN apk --no-cache add build-base git openssh-client

ENV INTERPOLATOR_VERSION 0.9.1

RUN mkdir -p /src/{cloudmon,interpolator}

COPY . /src/cloudmon
RUN cd /src/cloudmon && make build

# interpolator is required
RUN git clone https://github.com/dreitier/interpolator.git /src/interpolator \
    && cd /src/interpolator \
    && git checkout ${INTERPOLATOR_VERSION} \
    && make build